---

- hosts: all
  tasks:
  - name: Set timezone to Europe/Amsterdam
    become: yes
    timezone:
      name: Europe/Amsterdam

  - name: Install postgres
    become: yes
    apt:
      name: postgresql

  - name: install python packages
    become: yes
    pip:
      name:
        - xlrd
        - num2words
        - xlwt
        - phonenumbers
        - qrcode

      executable: pip3

  - name: Install packages
    become: yes
    apt:
      name:
        - python3
        - python3-pip
        - wget
        - bzr
        - git
        - gdebi-core

  - name: Install and config Odoo
    become: yes
    shell: wget -O - https://nightly.odoo.com/odoo.key | apt-key add - ; echo "deb http://nightly.odoo.com/11.0/nightly/deb/ ./" >> /etc/apt/sources.list ; apt-get update && apt-get install odoo -y


  - name: Create custom addons dir
    become: yes
    shell: mkdir -p /opt/odoo/addons

  - name: Config Odoo
    become: yes
    template:
      src: odoo.conf
      dest: /etc/odoo/

  - name: Restart Odoo
    become: yes
    service:
      name: odoo
      state: restarted

